id: 10_group
learningObjectives: 
- [Some learning objectives here]
hints:
- [Some hints here]
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Wow, some people convert after seeing just one item, can I create a group of these users to analyse later? (funnels > cohort)"

trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
            - "seven"
            - "7"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Interesting, that's good to know."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Not quite, try again"
