id: 3_best_day
learningObjectives: 
- [Some learning objectives here]
hints:
- [Some hints here]
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Running campaigns and want to know what day of the week is the most converting"
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
            - "Tuesday"
            - "Tue"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "That's interesting, good to know."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Not quite, try again"
