id: 5_funnel_conversion
learningObjectives: 
- "See how to easily find drops in the product and deep dive into it"
hints:
- "Click on 'Compare to past' next to the date filter and find different ways to compare your data"
- "Still stuck? Try our [docs](https://help.mixpanel.com/hc/en-us/articles/360019982652) or 'Request a solution'"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "First let's see if the order conversion has gone up or down compared to last month?"
        delay: 3500
      - text: "For that we'll try a different report type. Click on the funnels icon or select Funnels from the Reports menu."
        delay: 2500
      - text: "First step select the 'Item Detail Page' event and second is the 'Complete Purchase'"
        delay: 2500
      - text: "So what do you see? Up or Down?"
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
            - "Down"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Oh, that's not good. We need to figure out why."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Not quite, try again"

solution: 
  do:
    - actionId: bot_message
      params:
        person: keen
        messages: 
          - text: "Here's the end result https://mixpanel.com/s/351lUN or you can view as a funnel https://mixpanel.com/s/2ihGdm"

