id: 6_event_comparison
learningObjectives: 
- [Some learning objectives here]
hints:
- [Some hints here]
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "When you’re on an item page you can buy it, or add it to favourites, which is most common for our users?"
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
            - "Buying"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Interesting, that's good to know."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Not quite, try again"
