id: 7_consistent
learningObjectives: 
- [Some learning objectives here]
hints:
- [Some hints here]
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Is it consistent? Do we have any trends that shows why this conversion is low for X"
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
            - "something"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Interesting, that's good to know."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Not quite, try again"
