id: init_mixpanel_js
learningObjectives: 
- Analyzing log data 
hints:
- Try to find what all the users that drop in the funnel have in common
startFlow:
  do:
  - actionId: bot_message
    params:
      person: ness
      messages:
      - text: "So, I really need to start understanding our user actions"
        delay: 2000
      - text: "We want to implement Mixpanel. First go and create a new project"
        delay: 2000
      - text: "Then you can take the JS code to attach to the header of our app"
        delay: 2000
trigger:
  type: user_message
  params: 
    person: ness
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: mobile|android|ios|iphobe|non web
          flags: i
      then:
        do:
        - actionId: bot_message
          params:
            person: ness
            messages:
            - text: Good catch! I'll let the support team know.
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: ness
            messages:
            - text: Try again! I'm sure you'll figure this out.
              delay: 2500
